## Multiple Linear Regression

### Import the relevant libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

### Load the Data

In [2]:
data = pd.read_csv('1.02. Multiple linear regression.csv')

In [3]:
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [4]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

### Create the multiple Linear Regression

#### Declare independent, Dependent Variables

In [5]:
x = data[["GPA", "Rand 1,2,3"]]
y = data["SAT"]

In [6]:
x.shape

(84, 2)

In [7]:
y.shape

(84,)

### Regression

In [8]:
reg = LinearRegression()

In [9]:
reg.fit(x,y)

LinearRegression()

### r-squared

In [10]:
reg.score(x,y)

0.4060090730494814

In [11]:
reg.coef_

array([245.1771933 ,  -0.27790455])

In [12]:
reg.intercept_

np.float64(1029.347731366477)

#### Calculating the R-Squared

In [13]:
reg.score(x,y)

0.4060090730494814

#### Formula for Adjusted $R^2$

In [14]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]

adjusted_r2 = 1 - (1 - r2)*(n-1)/(n-p-1)
adjusted_r2

0.39134263040872785

#### Feature Selection (F-Regression)

In [15]:
from sklearn.feature_selection import f_regression

In [16]:
f_regression(x,y)

(array([56.04804786,  0.08259972]), array([7.19951844e-11, 7.74529835e-01]))

In [17]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 7.74529835e-01])

In [18]:
p_values.round(2)

array([0.  , 0.77])